# Generated by Django 4.2.1 on 2023-06-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tekst',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
