# Generated by Django 4.2.1 on 2023-05-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t77lehed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='0000000', upload_to='media'),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='0000000', max_length=20),
        ),
    ]
